const basicUser = {
  id: 'UGA383999',
  team_id: 'TF3F0EPOI',
  name: 'odile deray',
  deleted: false,
  color: 'e7392d',
  real_name: 'odile deray',
  tz: 'Europe/Brussels',
  tz_label: 'heure normale d’Europe centrale',
  tz_offset: 3600,
  profile: {
    title: '',
    phone: '',
    skype: '',
    real_name: 'odile deray',
    real_name_normalized: 'odile deray',
    display_name: 'odile',
    display_name_normalized: 'odile',
    status_text: '',
    status_emoji: '',
    status_expiration: 0,
    avatar_hash: 'g6bc46c67708',
    image_24: 'https://secure.gravatar.com/avatar/6bc46c67708f5d58c51869b353d8929b.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F00b63%2Fimg%2Favatars%2Fava_0020-24.png',
    status_text_canonical: '',
    team: 'TF3F0EX5W',
  },
  is_admin: false,
  is_owner: false,
  is_primary_owner: false,
  is_restricted: false,
  is_ultra_restricted: false,
  is_bot: false,
  is_app_user: false,
  updated: 1550342218,
  has_2fa: false,
};

const deletedUser = {
  id: 'UGA383993',
  team_id: 'TF3F0EPOI',
  name: 'perceval',
  deleted: true,
  color: 'e7392d',
  real_name: 'perceval',
  tz: 'Europe/Brussels',
  tz_label: 'heure normale d’Europe centrale',
  tz_offset: 3600,
  profile: {
    title: '',
    phone: '',
    skype: '',
    real_name: 'perceval',
    real_name_normalized: 'perceval',
    display_name: 'perceval',
    display_name_normalized: 'perceval',
    status_text: '',
    status_emoji: '',
    status_expiration: 0,
    avatar_hash: 'g6bc46c67708',
    image_24: 'https://secure.gravatar.com/avatar/6bc46c67708f5d58c51869b353d8929b.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F00b63%2Fimg%2Favatars%2Fava_0020-24.png',
    status_text_canonical: '',
    team: 'TF3F0EX5W',
  },
  is_admin: false,
  is_owner: false,
  is_primary_owner: false,
  is_restricted: false,
  is_ultra_restricted: false,
  is_bot: false,
  is_app_user: false,
  updated: 1550342218,
  has_2fa: false,
};

const botUser = {
  id: 'UGA383991',
  team_id: 'TF3F0EPOI',
  name: 'mr bot',
  deleted: false,
  color: 'e7392d',
  real_name: 'mr bot',
  tz: 'Europe/Brussels',
  tz_label: 'heure normale d’Europe centrale',
  tz_offset: 3600,
  profile: {
    title: '',
    phone: '',
    skype: '',
    real_name: 'mr bot',
    real_name_normalized: 'mr bot',
    display_name: 'mr bot',
    display_name_normalized: 'mr bot',
    status_text: '',
    status_emoji: '',
    status_expiration: 0,
    avatar_hash: 'g6bc46c67708',
    image_24: 'https://secure.gravatar.com/avatar/6bc46c67708f5d58c51869b353d8929b.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F00b63%2Fimg%2Favatars%2Fava_0020-24.png',
    status_text_canonical: '',
    team: 'TF3F0EX5W',
  },
  is_admin: false,
  is_owner: false,
  is_primary_owner: false,
  is_restricted: false,
  is_ultra_restricted: false,
  is_bot: true,
  is_app_user: false,
  updated: 1550342218,
  has_2fa: false,
};

const appUser = {
  id: 'UGA383992',
  team_id: 'TF3F0EPOI',
  name: 'swagg app',
  deleted: false,
  color: 'e7392d',
  real_name: 'swagg app',
  tz: 'Europe/Brussels',
  tz_label: 'heure normale d’Europe centrale',
  tz_offset: 3600,
  profile: {
    title: '',
    phone: '',
    skype: '',
    real_name: 'swagg app',
    real_name_normalized: 'swagg app',
    display_name: 'swagg app',
    display_name_normalized: 'swagg app',
    status_text: '',
    status_emoji: '',
    status_expiration: 0,
    avatar_hash: 'g6bc46c67708',
    image_24: 'https://secure.gravatar.com/avatar/6bc46c67708f5d58c51869b353d8929b.jpg?s=24&d=https%3A%2F%2Fa.slack-edge.com%2F00b63%2Fimg%2Favatars%2Fava_0020-24.png',
    status_text_canonical: '',
    team: 'TF3F0EX5W',
  },
  is_admin: false,
  is_owner: false,
  is_primary_owner: false,
  is_restricted: false,
  is_ultra_restricted: false,
  is_bot: false,
  is_app_user: true,
  updated: 1550342218,
  has_2fa: false,
};

module.exports = {
  basicUser,
  deletedUser,
  botUser,
  appUser,
};
